import type { PrismTheme } from 'prism-react-renderer';

/**
 * One top-level navbar item. The number of entries in `nav` equals the number
 * of main menu items (plus any items added by plugins, e.g. search).
 *
 * Use `docsPath` for content-backed menus: each one gets an autogenerated
 * sidebar scoped to `<mdxRoot>/<docsPath>`, keyed by its `label`.
 */
export type NavItem =
  | {
      label: string;
      /**
       * Directory under `mdxRoot` whose tree is shown as an autogenerated sidebar
       * when this menu is active. Set to `'.'` to use the whole `mdxRoot`.
       */
      docsPath: string;
      position?: 'left' | 'right';
      className?: string;
    }
  | {
      label: string;
      /**
       * Link destination. Internal paths (e.g. `/blog`) are rendered as
       * baseUrl-aware client-side routes; absolute URLs (`https://…`, `//cdn…`,
       * `mailto:`, `tel:`) are rendered as plain anchors.
       */
      href: string;
      position?: 'left' | 'right';
      className?: string;
      'aria-label'?: string;
    }
  | {
      /** Raw HTML navbar item (e.g. the classic GitHub icon). */
      html: string;
      position?: 'left' | 'right';
      className?: string;
    };

export interface SiteThemeConfig {
  /** OpenGraph / social card image URL or path under `static/`. */
  image?: string;
  favicon?: string;
  metadata?: { name: string; content: string }[];
  prism?: {
    light?: PrismTheme;
    dark?: PrismTheme;
    magicComments?: Array<Record<string, unknown>>;
  };
  imageZoom?: { selector?: string };
  liveCodeBlock?: { playgroundPosition?: 'top' | 'bottom' };
}

/**
 * The single call-to-action button rendered in the homepage hero.
 * Internal paths (e.g. `/intro`) are rendered with Docusaurus `<Link>` and
 * are automatically baseUrl-aware; absolute URLs (`https://…`, `//cdn…`,
 * `mailto:`, `tel:`) are rendered as external anchors with
 * `target="_blank"` and `rel="noopener noreferrer"`.
 */
export interface HeroButton {
  label: string;
  /** Link destination; internal or external is auto-detected from the value. */
  href: string;
}

/**
 * Secondary text link rendered directly below the hero button. Use it for
 * lower-emphasis destinations (changelog, pricing page, external reference).
 * When omitted — or when `label`/`href` is empty — nothing is rendered.
 */
export interface HeroLink {
  label: string;
  href: string;
}

/**
 * Homepage hero configuration. Read at runtime by the packaged
 * `src/pages/index.js`; consumers can override individual fields here
 * without swapping the whole page.
 */
export interface HeroConfig {
  /** Hero heading. Defaults to `DocsConfig.title`. */
  title?: string;
  /** Hero sub-heading. Defaults to `DocsConfig.tagline`. */
  subtitle?: string;
  /**
   * Preset Infima color variant applied to the hero. Set to `'none'` (or
   * provide `background.color`) to opt out of the preset and rely on your
   * own background/text colors.
   */
  variant?: 'primary' | 'dark' | 'secondary' | 'none';
  /** Background overrides. `color` and `image` can be combined. */
  background?: {
    /** Any CSS color value (hex, rgb(), `linear-gradient(...)`, …). */
    color?: string;
    /**
     * Absolute URL (`https://…`) or a path served from `static/`
     * (e.g. `img/hero.jpg`). Relative paths are auto-prefixed with `baseUrl`
     * so a single config works under any deploy path.
     */
    image?: string;
    /**
     * Translucent color layered on top of `image` to improve text
     * contrast (e.g. `rgba(0, 0, 0, 0.45)`). Ignored when `image` is unset.
     */
    overlay?: string;
  };
  /**
   * Call-to-action button. Set to `false` to hide it entirely.
   * When omitted, a default button points at the `intro` page under
   * `docsRouteBasePath` (e.g. `/docs/intro`, or `/intro` when the route is `/`).
   */
  button?: false | HeroButton;
  /**
   * Optional text link rendered directly below the button. When omitted or
   * missing `label`/`href`, nothing is rendered there.
   */
  link?: HeroLink;
  /**
   * Hide the default hero entirely. Usually paired with a consumer-provided
   * `<siteDir>/src/pages/index.js` that renders its own hero.
   */
  hidden?: boolean;
}

/**
 * Docs site options. `mdxRoot` is the content root; `nav` only lists top-bar
 * items. Each nav item with `docsPath` produces one autogenerated sidebar
 * (the sidebar id equals the item's label).
 */
export interface DocsConfig {
  title: string;
  /** Navbar title; defaults to `title`. */
  name?: string;
  tagline?: string;
  /** Logo URL or path under `static/` (e.g. `img/logo.svg`). When omitted, the
   *  navbar renders title-only (no image). */
  logo?: string;
  url: string;
  baseUrl: string;
  /**
   * Static directories relative to the consumer siteDir, or absolute paths.
   * Defaults to `['static']` when the siteDir has one. The package also adds
   * its own `assets/static` as a fallback.
   */
  staticDirectories?: string[];
  /**
   * Folder containing every `.md` / `.mdx` (relative to the consumer siteDir).
   * Sidebars are generated from this tree; defaults to `./docs`.
   */
  mdxRoot?: string;
  /** Docs plugin `routeBasePath`; defaults to `'docs'`. Drives the default hero “intro” link. */
  docsRouteBasePath?: string;
  /**
   * Homepage hero configuration. When omitted, a default hero is rendered
   * using `title`, `tagline` and a button to the `intro` page under `docsRouteBasePath`.
   */
  hero?: HeroConfig;
  /** Top navigation; each entry becomes one menu item. */
  nav: NavItem[];
  /** Label used in the default footer "Docs" column; defaults to `Docs`. */
  docMenuLabel?: string;
  copyright?: string;
  /** Set `false` to disable the blog preset. Defaults to `true`. */
  blog?: boolean;
  footer?: {
    style?: 'light' | 'dark';
    links?: Array<{
      title?: string;
      items: Array<
        | {
            label: string;
            /**
             * Link destination. Internal paths (e.g. `/blog`) become
             * baseUrl-aware client-side routes; absolute URLs (`https://…`,
             * `//cdn…`, `mailto:`, `tel:`) are rendered as plain anchors.
             */
            href: string;
          }
        | { html: string }
      >;
    }>;
  };
  theme?: SiteThemeConfig;
  externalStylesheets?: string[];
  externalScripts?: string[];
}

export declare function defineConfig(config: DocsConfig): DocsConfig;

export interface GetDocusaurusConfigOptions {
  siteDir?: string;
  /**
   * Absolute or siteDir-relative path to a specific `docs.config.*` file.
   * When omitted, the loader auto-discovers one in `siteDir`.
   * Also configurable via the CLI flag `--config <path>`
   * or the env var `DOCS_CONFIG`.
   */
  docsConfig?: string;
}

/** Full Docusaurus config object (advanced use; prefer the `docs` CLI). */
export declare function getDocusaurusConfig(
  options?: GetDocusaurusConfigOptions | string
): Record<string, unknown>;
